- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install collectd
      apt: name={{item}} state=installed update_cache=yes
      with_items:
        - collectd
        - collectd-utils
    - name: Copy config
      copy:
        src: collectd.conf
        dest: /etc/collectd/collectd.conf
    - name: Restart collectd
      systemd:
        name: collectd.service
        state: restarted
        
